# Generated by Django 6.0.7 on 2026-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('metals', 'معدنيات'), ('devices', 'أجهزة'), ('materials', 'مواد')], max_length=20),
        ),
    ]
